/**
 * Last name: Shah
 * First name: Karan
 * Period: 2
 * 
 * In this lab you will practice calling boolean methods of an Elevator class that has
 * been written for you. Follow the directions given in the comments. You will need
 * to use System.out.println (String) to print messages to the console.
 * 
 * After you have filled in the instructions, copy and paste the program into Code Check.
 * The link is provided on canvas. Once you get the program to pass, download the
 * zipped file generated by Code Check. DO NOT open or unzip this file. Submit the zipped file 
 * on Canvas. 
 *
 */
public class UseElevator {

	public static void main(String[] args) {
		//Create an elevator object using a no-argument (default) constructor
		Elevator sample = new Elevator();
		

		//Call the isOutOfRange(floor) method to check if floor number -2 is a valid floor, 
		//if not print an error message, "Error: The floor must be between 1 and 20". 
		//Otherwise print "Happy Landing ..."
		if(!sample.isOutOfRange(-2)){
			System.out.println("Happy Landing ...");
		}
		else{
			System.out.println("Error: The floor must be between 1 and 20");
		}

		//Call the isOutOfRange(floor) method to check if floor number 0 is a valid floor, 
		//if not print an error message, "Error: The floor must be between 1 and 20". 
		//Otherwise print "Happy Landing ..."
		if(!sample.isOutOfRange(0)){
			System.out.println("Happy Landing ...");
		}
		else{
			System.out.println("Error: The floor must be between 1 and 20");
		}
		
		//Call the isOutOfRange(floor) method to check if floor number 22 is a valid floor, 
		//if not print an error message, "Error: The floor must be between 1 and 20". 
		//Otherwise print "Happy Landing ..."
		if(!sample.isOutOfRange(22)){
			System.out.println("Happy Landing ...");
		}
		else{
			System.out.println("Error: The floor must be between 1 and 20");
		}

		//Call the isOutOfRange(floor) method to check if floor number 13 is a valid floor, 
		//if not print an error message, "Error: The floor must be between 1 and 20". 
		//Otherwise print "Happy Landing ..."
		if(!sample.isOutOfRange(13)){
			System.out.println("Happy Landing ...");
		}
		else{
			System.out.println("Error: The floor must be between 1 and 20");
		}

		//Call the is13thFloor(floor) method to check if floor number is 13. If it is print 
		//an error message, "Error: There is no 13th floor". Otherwise print "Happy Landing!"
		if(!sample.is13thFloor(13)){
			System.out.println("Happy Landing!");
		}
		else{
			System.out.println("Error: There is no 13th floor");
		}

		//Use the isAbove13(floor) method and print the floor number, if the floor is below 13, 
		//otherwise print a floor number one less than the floor number. Pass in floor number 4.
		if(!sample.isAbove13(4)){
		   System.out.println(4);
		}
      else{
         System.out.println(5);
      }



		//Use the isAbove13(floor) method and print the floor number, if the floor is below 13, 
		//otherwise print a floor number one less than the floor number. Pass in floor number 15.
      if(!sample.isAbove13(15)){
		   System.out.println(15);
		}
      else{
         System.out.println(14);
      }

		
	}

}
